joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 20

base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'l_wheel_joint'
  right_wheel : 'r_wheel_joint'
  publish_rate: 20.0               # default: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  enable_odom_tf: true

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.8
  wheel_radius : 0.1

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.5

  # Base frame_id
  base_frame_id: base_footprint #default: base_link
  odom_frame_id: odom

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.5 # m/s
      # min_velocity           : -0.15 # m/s
      has_acceleration_limits: true
      max_acceleration       : 2.0  # m/s^2
      # min_acceleration       : -1.6 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 4.0  # rad/s^2